import { ShipmentForm } from "../interface/form";

const shipmentDefaultValue = {
  billNo: "9777",
  carrierId: 1,
  carrierReferenceNo: "",
  shipperName: "ideal courier",
  shipperMail: "",
  shipperAddress: "",
  shipperContact: "",
  receiverName: "",
  receiverMail: "",
  receiverPrimaryAddress: "",
  receiverSecondaryAddress: "",
  receiverPrimaryContact: "",
  receiverSecondaryContact: "",
  shipmentType: "domestic",
  weight: "",
  courier: "",
  packages: "",
  mode: "normal",
  product: "",
  quantity: "",
  paymentId: "",
  totalFreight: "",
  origin: "",
  destination: "",
  departureTime: "",
  pickupDate: "",
  pickupTime: "",
  deliveryDate: "",
  comment: "",
  date: "",
  time: "",
  location: "",
  statusId: 1,
  remarks: "",
  isDraft: 0,
};

export { shipmentDefaultValue };
